### Site Settings ###
title               : Fábio Marquez
description         : >-
                      Olá, seja bem-vind@! Conheça <a href="https://fabiomarquez.github.io/portfolio/">meus projetos</a> ou explore <a href="https://fabiomarquez.github.io/blog/">minhas publicações</a>.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : 
remote_theme        : 


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/projects.html



### Author Info ###
author:
  name              : Fábio Júnior
  image             : https://github.com/fabiomarquez/fabiomarquez.github.io/blob/main/welcomeblue.gif?raw=true
# behance           : your_username
# dribbble          : your_username
  email             : fabiomarquezc@gmail.com
# facebook          : your_username
  github            : fabiomarquez
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : fabio-marquez
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /portfolio/:name



### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
